# -*- coding: utf-8 -*-
"""ProgramData_19081010163

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11wTbSGBmqNmJZbv4-8x8Cv56ClIOmQ8_

Program Ini digunakan untuk mengolah data Excel, untuk mencari Mean,Median,Modus,Varian dan Standard Deviasi. terdiri dari dua tahap yaitu Pengelolahan Data dan Penyajian Data

Disarankan untuk menginstal Pandas dan matplotib terlebih dahulu

# Pengolahan Data

Pada tahap ini dimana data diolah untuk menemukan Mean,Median,Modus,Varian dan Standard Deviasi,dengan bantuan pandas dan import CSV.

Pandas

Pandas sendiri berfungsi untuk membaca dan mengambil data dari excel, pemanggilan tersebut dengan memangil nama kolom didalamnya.didalam excel saya terdapat kolom masukan yang sebagai hasil inputan dari survey, dari itu Pandas mengambil angka-angka yang telah adalah dalam satu kolom.

Import CSV

Import CSV sama seperti Pandas namun disini hanya bertugas sebagai perantara jadi juga diberikan arah kolom mana yang akan digunakan, disini saya mengambil row[6] yang berarti kolom tersebut berupa masukan survey.


#Mean 
Sumtotal sebagai jumlah total dari data tersebut dan Samplesize untuk mengambil sample data,data_list merupakan list data didalam excel kemudian row[6] berfungsi untuk mengambil kolom ke 6 dalam excel yaitu kolom masukan sehingga kolom tersebut yang akan diolah. kemudian total data akan dibagi jumlah data tersebut maka keluarlah nilai mean
"""

import csv
import pandas as pd

#pengolahandata
#1.mean
#2.median
#3.modus
#4.kuartil
#5.varian
#6.standard deviasi
#penyajian data
#1.distribusidrekuensi

i=0
data_list = []
with open ('/content/drive/My Drive/Colab Notebooks/Survery difilter - data.csv') as myfile:
  data = csv.reader(myfile)
  for row in data:
    i += 1
    data_list.append(row)
    if i > 1000:
      break

excel = pd.read_excel('/content/drive/My Drive/Colab Notebooks/Survery difilter.xlsx')
a = excel['masukan']
print("===========================================  Pengolahan Data Survey  ===========================================")
print("                                       Survey Lama Pemakaian Sosial Media                                        \n")
print(excel)

#mean
sumtotal= 0
samplesize =0
for row in data_list[1:]:
  sumtotal = int(row[6])+sumtotal
  samplesize +=1
ratarata = sumtotal/samplesize
print('Mean adalah',ratarata)

"""# Modus
Paramatermodus merupakan jarak/total data dalam satu kolom,nilai modus merupakan tempat untuk menyimpan hasil dari perhitungan modus.Angka yang dihitung merupakan angka berapa saja yang ada didalam kolom masukan dan banyak angka merupakan jumlah angka yang terdapat didalam data. Tahap yang pertama yaitu mencari range data didalam data kemudian tahap kedua angka berapa saja yang muncul didalam data tersebut di variabelkan dalam angkayangmaudihitung. setelah itu tahap ketiga mencari berapa kali angka tersebut muncul divariabel kan dalam banyak angka. Maka dari itu diketahui jumlah angka yang sering muncul yaitu 120 sebanyak 10 kali
"""

#modus
parameterModus = 0
nilaiModus = []
angkaYangMauDiHitung = 0
banyakAngka = 1
for i in range(1, len(a)):
    if (a[i] == angkaYangMauDiHitung):
        banyakAngka += 1
    else:
        if (banyakAngka > parameterModus):
            parameterModus = banyakAngka
            nilaiModus = []
            nilaiModus.append(angkaYangMauDiHitung)
        elif (banyakAngka == parameterModus):
            nilaiModus.append(angkaYangMauDiHitung)
        angkaYangMauDiHitung = a[i]
        banyakAngka = 1
if (banyakAngka > parameterModus):
    parameterModus = banyakAngka
    nilaiModus = []
    nilaiModus.append(angkaYangMauDiHitung)
elif (banyakAngka == parameterModus):
    nilaiModus.append(angkaYangMauDiHitung)
print("Modus adalah",nilaiModus)

"""# Median
Meadianmas merupakan variabel untuk menyimpan hasil dari perhitungan median,Def median(elem) untuk fungsi mencari median, menggunakan elemen[6] disingkat elem[6] hal ini masih sama dengan row[6] pada perhitungan mean untuk mencari kolom yang akan digunakan.Data_list merupakan list dari data,kemudian sort(key=meadian) untuk memanggil fungsi meadian. samplesize = len(data_list) berapa jumlah data yang terdapat satu kolom.Middle untuk mengambil nilai tengah dengan cara samplesize dibagi dengan 4, maka medianmas akan bertindak untuk menyimpan data hasil pembagian.
"""

#median
medianmas=0
def meadian(elem):
  return elem[6]
data_list.sort(key=meadian)
samplesize = len(data_list)
middle = samplesize/4
medianmas = data_list[int(round(middle))]
print('median adalah',medianmas[6])

"""# Kuartil
Sortedata berfungsi untuk menyimpan hasil sorti data.tahap pertama yaitu membagi jumlah data dengan cara memisahkan jarak angka pertama sampai nilai tengah kemudian nilai tengah sampai nilai akhir,Tahap Kedua yaitu perhitungan q1 merupakan variabel untuk menyimpan hasil dari pehitungan samplesize.sample ini merupakan bagian pertama dari hasil sorti dari nomor 1-38 kemudian dikalikan 0,25 dan quartil3 38-50 dikalikan dengan 0.5.kemudian quartil1 sebgaia variabel menyimpan sorteddata di q1
"""

#quartil
sorteddata = []
for row in data_list[1:]:
  if row[6] != 0:
    sorteddata.append((row[6]))
sorteddata.sort()
samplesize = len(sorteddata)
q1 = samplesize*0.26
q3 = samplesize*0.5
quartil1 = sorteddata[round(q1)]
quartil3 = sorteddata[round(q3)]
print("Kuartil1 adalah",quartil1)
print("kuartil3 adalah",quartil3)

"""# Varian

Jumlah untuk mengambil jumlah data kolom masukan, kemudian m untuk mengambil mean(ratarata), dan total untuk variabel hasil perhitungan,tahap pertama menentukan range di data kemudian total kolom a dikurangi mean dikali 2. tahap terakhir variansi total dibagi jumlahdata-1, hasil perhitungan tersebut disimpan dalam variabel variansi.
"""

#varian
jumlah = len(a)
m = ratarata
total = 0
for i in range(jumlah):
  total += (a[i]-m)**2

variansi= total/(jumlah-1)
print("varian adalah",variansi)

"""# Standard Deviasi
Array berfungsi untuk mengambil dan menyimpan data kolom masukan, tahap pertama menentukan banyak data data dalam kolom setelah itu menentukan jumlah data dalam satu kolom setelah ditemukan selanjutnya jumlah data/banyak data menghasilkan rata,kemudian jumlah data dikurangi rata diklaikan 2, hasil perhitungan tersebut disimpan dalam variabel hitung.kemudian pembagian sigma(hitung) dibagi panjang array, tahap terakhir standar deviasi variabel pembagian dikalikan 0.5 dan menghasilkan perhitungan standar deviasi.

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame
See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

Kode ini tidak mempengaruhi proses dan hasil perhitungan dikarenakan sebelumnya menggunakan dua importan untuk membaca data excel yaitu menggunakan import csv dan pandas. sehingga terjadi kesamaan antar data.
"""

#standarddeviasi
array= a
for i in range(len(array)):
    array[i]=int(array[i])
jumlah=0
for i in range(len(array)):
    jumlah +=array[i]
rata=jumlah/len(array)
sigma = 0
for i in range(len(array)):
    hitung =(array[i]-rata)**2
    sigma += hitung
pembagianN=sigma/len(array)
standarDeviasi=pembagianN ** 0.5
print("Standar deviasi adalah",standarDeviasi,"\n")

"""# Penyajian Data


Tahap Penyajian data ini menampilkan dua tabel data yaitu Data Tunggal,untuk diagram grafik saya menggunakan Data Tunggal sebagai sumber karena mudah dibaca daripada menggunakan data tunggal sebagai sumber data

#Tabel Data

Dalam tabel ini saya menampilkan Data frekuensi, distribusi, kumulatif, relatif dan kumulatif relatif, dengan menggunakan fungsi dari Matplotib untuk menampilkan diagram grafik, ogive, lingkaran. Panda berfungsi untuk membaca data dalam tabel sehingga di simpan dalam variabel Tunggal kemudian memanggil Variabel tersebut untuk mencetak tabel
"""

import pandas as pd
import matplotlib.pyplot as plt

tunggal = pd.read_excel("/content/drive/My Drive/Colab Notebooks/distribusifrekuensi_tunggal.xlsx")
b = tunggal['Data']
c = tunggal['Distribusifrekuensi']
tunggal

"""#Diagram Batang | Disitribusi Frekuensi

Array y berfungsi untuk menampilkan tinggi/banyak nilai muncul dalam satu nilai data nilai tersebut dimasukan pada array x yang berisikan data yang dimasukan ke dalam kolom,kemudian mebentuk panjang dan tinggi diagram dengan Figure panjang 15 dan tinggi 5. Fungsi bar untuk menampilkan diagram Batang.
"""

#diagram batang
y=[3,1,2,5,2,10,1,3,3,2,1,8,2,2,1,2,1,1]
x=['30','40','45','60','90','120','140','150','180','240','270','300','360','480','500','600','720','800']
plt.figure(figsize=(15,5))
plt.bar(x,y)
plt.title('Distribusi Frekuensi')
plt.ylabel('data')
plt.xlabel('nilai muncul')

plt.show()

"""#Diagram Ogive | Disitribusi Frekuensi

Array y berfungsi untuk menampilkan tinggi/banyak nilai muncul dalam satu nilai data nilai tersebut dimasukan pada array x yang berisikan data yang dimasukan ke dalam kolom,kemudian mebentuk panjang dan tinggi diagram dengan Figure panjang 15 dan tinggi 5. Fungsi plot untuk menampilkan diagram Ogive/garis.
"""

#diagram ogive
y=[3,1,2,5,2,10,1,3,3,2,1,8,2,2,1,2,1,1]
k=[3,4,6,11,13,22,23,26,28,30,31,39,41,43,44,46,47,48]
plt.figure(figsize=(15,5))
plt.plot(x,y)
plt.title('Distribusi Frekuensi')
plt.ylabel('nilai muncul')
plt.xlabel('data')

plt.show()

"""#Diagram Lingkaran | Disitribusi Frekuensi

Array y berfungsi untuk menampilkan lebar/banyak nilai muncul dalam satu nilai data nilai tersebut dimasukan pada array x yang berisikan data yang dimasukan ke dalam kolom,kemudian mebentuk panjang dan tinggi diagram dengan Figure panjang 15 dan tinggi 10. Fungsi pie untuk menampilkan diagram lingkaran.
"""

#diagram Lingkaran
slice = [3,1,2,5,2,10,1,3,3,2,1,8,2,2,1,2,1,1]
labels= ['30','40','45','60','90','120','140','150','180','240','270','300','360','480','500','600','720','800']
plt.figure(figsize=(15,10))
plt.pie(slice,labels=labels)
print("Distribusi Frekuensi")
plt.show()